name: build-toolc-gcc12-deb11-arm64
run-name: Build toolc-gcc12-deb11-arm64
on:
  push:
    branches:
      - master

jobs:
  job1:
    if: contains(github.event.head_commit.message, 'build-toolc-gcc12-deb11-arm64') == true
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Set env
        run: echo "CURR_DATE=$(date +'%Y%m%d')" >> "$GITHUB_ENV"
      - name: Set env
        run: echo "PICK_TAG=gcc12-deb11-arm64" >> "$GITHUB_ENV"
      - name: Set env
        run: echo "OCIIMG_NAME=tg-focus-cicd-toolc" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
        with:
          ref: master
      - run: df -h
      - name: Build
        run: bash ci/toolc-${{ env.PICK_TAG }}.bash
      - run: buildah ps
      - run: df -h
      - run: ls -l
      - run: ls -l ci
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OCIIMG_NAME }}-${{ env.PICK_TAG }}.tar
          path: ci/${{ env.OCIIMG_NAME }}-${{ env.PICK_TAG }}.tar
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OCIIMG_NAME }}-${{ env.PICK_TAG }}.json
          path: ci/${{ env.OCIIMG_NAME }}-${{ env.PICK_TAG }}.json
      - uses: actions/upload-artifact@v4
        with:
          name: CHECKSUMS
          path: ci/CHECKSUMS
